In [190]:
import stim
import numpy as np
from sklearn.model_selection import train_test_split

distance=3
num_ancilla_qubits=8
rounds=5

surface_code_circuit = stim.Circuit.generated(
    "surface_code:rotated_memory_x",
    rounds=5,
    distance=3,
    after_clifford_depolarization=0.01,
    after_reset_flip_probability=0.01,
    before_measure_flip_probability=0.01,
    before_round_data_depolarization=0.01)

num_shots=64*1000
# Compile the sampler
sampler = surface_code_circuit.compile_detector_sampler()
# Sample shots, with observables
detection_events, observable_flips = sampler.sample(num_shots, separate_observables=True)


detection_events = detection_events.astype(int)
detection_strings = [''.join(map(str, row)) for row in detection_events] #compress the detection events in a tensor
detection_events_numeric = [[int(value) for value in row] for row in detection_events] # Convert string elements to integers (or floats if needed)
detection_array = np.array(detection_events_numeric) # Convert detection_events to a numpy array
print(detection_array[0])

detection_array1 = detection_array.reshape(num_shots, rounds, num_ancilla_qubits) #first dim is the number of shots, second dim round number, third dim is the Ancilla 
print(detection_array1[0]) 

observable_flips = observable_flips.astype(int).flatten().tolist()

[0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1]
[[0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 1]]


In [191]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchviz import make_dot
import torch.nn.functional as F



class LatticeRNNCell(nn.Module):
    def __init__(self, input_size, hidden_size,batch_size):
        super(LatticeRNNCell, self).__init__()
        self.batch_size=batch_size
        self.hidden=hidden_size
        self.fc_input = nn.Linear(input_size, input_size)
        self.fc_hidden_double = nn.Linear(hidden_size*2, hidden_size)
        self.fc_hidden_single = nn.Linear(hidden_size, hidden_size)
        self.rnn_cell = nn.RNNCell(input_size, hidden_size)

    def forward(self, x, hidden_left, hidden_up):
        # if hidden_left is not None and hidden_bottom is not None:
        #     hidden = (hidden_left + hidden_bottom) / 2  # Average of left and bottom
        # elif hidden_left is not None:
        #     hidden = hidden_left
        # elif hidden_bottom is not None:
        #     hidden = hidden_bottom
        # else:
        #     hidden = torch.zeros(x.size(0), self.hidden_size).to(x.device)  # Initial hidden state
        
        #input fc net
        #input=self.fc_input(x.type(torch.FloatTensor))

        # Combine the hidden states from left and bottom
        if hidden_left is not None and hidden_up is not None:
            combined_hidden=torch.cat((hidden_left,hidden_up),1)
            hidden=self.fc_hidden_double(combined_hidden.squeeze(0))

        elif hidden_left is not None:
            hidden=self.fc_hidden_single(hidden_left)

        elif hidden_up is not None:
            hidden=self.fc_hidden_single(hidden_up)
            
        else:
            hidden=torch.zeros(self.batch_size,self.hidden, dtype=torch.float)

        x=x.squeeze(1).float()

        # Update hidden state using current input and combined hidden state
        hidden = self.rnn_cell(x, hidden)
        
        return hidden

class LatticeRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, grid_height, grid_width,batch_size):
        super(LatticeRNN, self).__init__()
        self.hidden_size = hidden_size
        self.batch_size = batch_size
        self.grid_height = grid_height
        self.grid_width = grid_width 
        self.rnn_cells = nn.ModuleList([LatticeRNNCell(input_size, hidden_size,batch_size) for _ in range(grid_height * grid_width)])
        self.fc_hidden = nn.Linear(hidden_size, hidden_size)
        self.fc_out = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()  # For binary output
    
    def forward(self, x, hidden_ext):
        # Initialize a grid of hidden states
        grid = [[None for _ in range(self.grid_width)] for _ in range(self.grid_height)]
        
        # Reshape the input to match the grid size
        batch_size, seq_len, _ = x.size()
        x = x.reshape(batch_size, self.grid_height, self.grid_width)

        for i in range(self.grid_height):
            for j in range(self.grid_width):
                input_bit = x[:,i,j].unsqueeze(1).unsqueeze(1) # Get the input for the current cell
                if j==0 & i==0:
                    hidden_left = hidden_ext
                hidden_left = grid[i][j - 1] if j > 0 else None
                hidden_up = grid[i - 1][j] if i > 0 else None

                # Get the index for the current RNN cell
                cell_index = i * self.grid_width + j
                hidden = self.rnn_cells[cell_index](input_bit, hidden_left, hidden_up)

                # Store the hidden state in the grid
                grid[i][j] = hidden

        # The output that matters is the hidden state from the top-right corner (i.e., grid[grid_size-1][grid_size-1])
        bottom_right_hidden = grid[-1][-1]

        # Pass the hidden state through the fully connected layer and sigmoid for binary output
        hidden= self.fc_hidden(bottom_right_hidden)
        output = self.fc_out(bottom_right_hidden)
        output = self.sigmoid(output)

        return output, hidden
    


# RNN model
class BlockRNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, grid_height, grid_width, rounds,batch_size):
        super(BlockRNN, self).__init__()
        self.hidden_size = hidden_size
        self.batch_size = batch_size
        self.fc_in = nn.Linear(input_size, input_size)
        self.rnn_block = LatticeRNN(input_size, hidden_size, output_size, grid_height, grid_width,batch_size)
        self.fc_out = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()  # For binary output
    
    def forward(self, x, rounds):
        #input=self.fc_in(x)

        hidden_ext = torch.zeros(1,1,self.hidden_size)

        for round in range (rounds):
            input_block = x[:,round,:].unsqueeze(2)  # (1, 8)
            out, hidden_ext = self.rnn_block(input_block, hidden_ext)

        #I already use fc, sigmoid in the LatticeRNN
        #out = self.fc_out(out)  # Use the last time-step's output, needed for changing the dimension of the output compared of input
        #out = self.sigmoid(out)  # I need a Binary output
        return out, hidden_ext
    
    def init_hidden(self, batch_size):
        return torch.zeros(1, batch_size, self.hidden_size)

In [192]:
def train_rnn(model, X_train, y_train, criterion, optimizer, num_epochs, batch_size,rounds):
    model.train()  # Set the model to training mode

    num_samples = len(X_train[:,0,0])
    
    for epoch in range(num_epochs):
        running_loss = 0.0
        
        for i in range(0, num_samples, batch_size):
            # Create mini-batches
            batch_x = torch.from_numpy(X_train[i:i + batch_size])
            batch_y = torch.Tensor(y_train[i:i + batch_size])

            # Zero the parameter gradients
            optimizer.zero_grad()

            # Forward pass
            #hidden = model.init_hidden(1)
            output, hidden = model(batch_x, rounds)

            # Compute loss
            loss = criterion(output.squeeze(1), batch_y)

            # Backward pass (compute gradients)
            loss.backward()

            # Optimize (update weights)
            optimizer.step()

            # Accumulate the loss for logging purposes
            running_loss += loss.item()

        # Print average loss after each epoch
        avg_loss = running_loss / (num_samples // batch_size)
        print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}")

    print("Training finished.")


# Example usage

In [193]:
def binary_array_to_tensor(binary_array):
    # Check if the input is a NumPy array, if not, convert it
    if isinstance(binary_array, np.ndarray):
        tensor = torch.from_numpy(binary_array).float()  # Convert NumPy array to float32 tensor
    else:
        # If not a NumPy array, convert it as before
        tensor = torch.tensor([[int(bit) for bit in binary_array]], dtype=torch.float32)
    return tensor.unsqueeze(0)  # Add batch dimension (batch_size = 1)


def test(model, test_sequences, targets,batch_size):
    model.eval()  # Set the model to evaluation mode (disable dropout, etc.)
    correct = 0

    hidden = None
    num_samples = len(test_sequences[:,0,0])
    
    
    with torch.no_grad():  # Disable gradient computation for testing
        for i in range(0, num_samples, batch_size):
            
            output=np.zeros(batch_size)
            batch_x = torch.from_numpy(test_sequences[i:i + batch_size])
            target = targets[i:i + batch_size]
            rounds = len(batch_x[0,:,0])
            
            # Initialize hidden state
            #if hidden is None:
                # Initialize hidden state for the first sequence (or batch)
            #    hidden = model.init_hidden(batch_size=1)  # batch_size might vary depending on your use case
            #else:
                #hidden=hidden.detach() #you detach if you want to avoid that the gradient is propagated through the hidden states to avoid long training time and memory usage
            
            # Forward pass for prediction
            output, hidden = model(batch_x, rounds)
            prediction = torch.round(output)  # Convert probability to binary (0 or 1)
            
            for j in range(0,batch_size):
                if prediction[j] == target[j]:
                    correct += 1
    
    accuracy = correct / len(test_sequences)
    print(f'Test Accuracy: {accuracy * 100:.2f}%')

In [194]:
# Example usage
input_size = 1  # Each RNN cell takes 1 bit as input
hidden_size = 8 # Hidden size of each RNN cell
output_size = 1  # Binary output
grid_height = 4  # 4x2 grid of RNN cells
grid_width= 2
batch_size = 64

model = LatticeRNN(input_size, hidden_size, output_size, grid_height, grid_width,batch_size)

# Input is a batch of binary sequences (batch_size, seq_len, input_size), reshaped to match grid size
seq_len = grid_height * grid_width  # Number of bits equal to the grid size squared
x = torch.randn(batch_size, seq_len, input_size)  # Random input, replace with binary input
hidden_ext = torch.randn(batch_size, hidden_size)  # Random input, replace with binary input

output, hidden = model(x,hidden_ext)
print(hidden)


tensor([[ 0.3062,  0.4015, -0.2562, -0.3896, -0.5514, -0.0314,  0.1505,  0.0270],
        [ 0.2465,  0.4035, -0.2727, -0.3833, -0.5616, -0.0133,  0.0472,  0.0846],
        [ 0.2950,  0.4290, -0.3010, -0.3025, -0.4334,  0.0086,  0.1513, -0.1035],
        [ 0.3192,  0.4385, -0.2344, -0.3907, -0.5375, -0.0356,  0.2179, -0.0477],
        [ 0.3422,  0.3191, -0.3343, -0.3070, -0.4557, -0.0264,  0.1090,  0.0442],
        [ 0.4217,  0.3554, -0.2596, -0.3383, -0.4226, -0.0451,  0.3365, -0.1198],
        [ 0.2907,  0.3915, -0.2952, -0.3299, -0.4855, -0.0123,  0.1034,  0.0133],
        [ 0.3113,  0.3758, -0.2907, -0.3444, -0.4933, -0.0217,  0.1315,  0.0126],
        [ 0.2349,  0.4226, -0.2889, -0.3539, -0.5222,  0.0049,  0.0420,  0.0297],
        [ 0.2229,  0.4013, -0.2868, -0.3709, -0.5487, -0.0009,  0.0035,  0.0950],
        [ 0.3017,  0.3150, -0.3609, -0.2890, -0.4520, -0.0075,  0.0202,  0.0850],
        [ 0.1088,  0.3646, -0.3313, -0.3827, -0.5830,  0.0297, -0.2163,  0.2385],
        [ 0.3636

In [195]:
# Hyperparameters
input_size = 1  # Each Lattice RNN cell takes 1 bit as input
hidden_size = 64  # Hidden size of each RNN cell
output_size = 1  # Binary output (e.g., 0 or 1)
grid_height = 2  # Number of rows in the grid
grid_width = 4   # Number of columns in the grid
learning_rate = 0.001
num_epochs = 10
batch_size = 64

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Create a model instance
model = BlockRNN(input_size, hidden_size, output_size, grid_height, grid_width, rounds,batch_size).to(device)

# Define loss function and optimizer
criterion = nn.BCELoss()  # Binary cross-entropy loss for binary classification
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

test_size=0.2
test_dataset_size=num_shots*test_size
X_train, X_test, y_train, y_test = train_test_split(detection_array1, observable_flips, test_size=0.2, random_state=42, shuffle=False)

# Training the model
train_rnn(model, X_train, y_train, criterion, optimizer, num_epochs,batch_size,rounds)

test(model, X_test, y_test,batch_size)

Epoch [1/10], Loss: 0.3981
Epoch [2/10], Loss: 0.3831
Epoch [3/10], Loss: 0.3794
Epoch [4/10], Loss: 0.3770
Epoch [5/10], Loss: 0.3753
Epoch [6/10], Loss: 0.3730
Epoch [7/10], Loss: 0.3715
Epoch [8/10], Loss: 0.3708
Epoch [9/10], Loss: 0.3728
Epoch [10/10], Loss: 0.3729
Training finished.
Test Accuracy: 86.29%
